### ISSUE TITLE
[BUG] Code block can't read in light mode (PaperMod migrate to PaperModX)

### ISSUE THREAD

**Issue by Triple-Z** [reorx/hugo-PaperModX#21]
**Describe the bug**

 - Device/Os: macOS
 - Type: Desktop
 - Browser and version [e.g. Chrome 86.0]: Chrome 103.0.5060.134
 - Hugo Version [ >=0.83.0 expected]: v0.101.0+extended
 - Theme Version [e.g. v4.0, master, or commit-id ]: 61452c190b57ed2c1246723e7fd1575ac4bf5a23

**Steps to reproduce the behavior:**

Using the `PaperModX` theme for my blog (it use `PaperMod` before).

The code in the code block cannot be read in light mode. If you switch to dark mode, it will be fine.

**Expected behavior**:

The code block can be read easily.

**Screenshots**

Light mode (also the four black corners maybe a "bug" too?)
<img width="850" alt="image" src="https://user-images.githubusercontent.com/16285716/183415368-ff931c64-f8e5-401b-9c73-9f634ce2fe04.png">

Night mode (it works well)
<img width="866" alt="image" src="https://user-images.githubusercontent.com/16285716/183415993-a21b4eac-7005-4763-97ab-5a8bbc175a37.png">

**Additional context**

You can preview the example page in here: https://test-papermodx.my-hugo-blog.pages.dev/posts/mastering-git-cherry-pick/

<details>
<summary>Current config file</summary>

```yaml
baseURL: "https://blog.triplez.cn/"
languageCode: "zh-cn"
defaultContentLanguage: "zh"
hasCJKLanguage: true
title: "TripleZ's Blog"
theme: "PaperMod"

disqusShortname: triplezs-blog
googleAnalytics: UA-xxxx-3

menu:
    main:
        # - identifier: categories
        #   name: Categories
        #   url: /categories/
        #   weight: 10
        - identifier: tags
          name: 标签 
          url: /tags/
          weight: 20
        - identifier: archives
          name: 归档
          url: /archives/
          weight: 30

params:
    env: production
    defaultTheme: auto # to switch between dark or light according to browser theme
    disableThemeToggle: false
    ShowBreadCrumbs: false
    ShowPostNavLinks: true
    TocSide: 'left'  # or 'right'
    EnableInstantClick: true
    author: ["TripleZ"]
    description: ""
    BeiAn: 粤ICP备xxxxx号
    comments: true
    ShowToc: true
    TocOpen: false
    ShowReadingTime: true
    ShowShareButtons: true
    ShowCodeCopyButtons: true
    fuseOpts: # for search
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    assets:
        favicon: "/favicon.ico"
        favicon16x16:  "/favicon-16x16.png"
        favicon32x32:  "/favicon-32x32.png"
        apple_touch_icon:  "/apple-touch-icon.png"
        safari_pinned_tab:  "/safari-pinned-tab.svg"

# for search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
  goldmark:
    renderer:
      unsafe: true # enable raw html in markdown
```
</details>
