### ISSUE TITLE
[BUG] Site logo does not show

### ISSUE THREAD

**Issue by istvnurbn** [reorx/hugo-PaperModX#30]
**Describe the bug**
When the site logo is set like the below, it does not show when the site is rendered.

```YML
label:
  text: "site name"
  icon: "logo.svg"
```

 - Device/Os: macOS
 - Type:: Desktop
 - Browser and version: Firefox 105.0.1  & Chromium 106.0.5249.61
 - Hugo Version: v0.104.2+extended
 - Theme Version: master

**Steps to reproduce the behavior:**
1. Set the label and icon as it is in the documentation.
2. `hugo server`
3. Logo does not show

**Expected behavior**:
The logo should show up left to the site's title.

**Screenshots**
N/A

**Additional context**
The header partial's logic is a bit different than the upstream PaperMod one.

**Comment by eremid** [comment]
Hello,

Try with :
```
params:
  logo:
     text: "coucou" (if empty = site.Title
     icon: "logo.png"
     iconHeight: 50 (default 30)
```
