### ISSUE TITLE
The TocSide does't work for me

### ISSUE THREAD

**Issue by aucker** [reorx/hugo-PaperModX#39]
Hi, sorry for this issue, but I have a question, I follow the guide to configure my `config.yml`, I add `TocSide: right` in it. But when I build it on my local machine, the toc works well, when I use `GitHub Actions`, the tocside doesn't work well, it is still at the top side rather left side.
![image](https://user-images.githubusercontent.com/41871212/202887311-35d4ae42-d93d-4b58-a6ba-099e5f14865d.png)

I tried both on GitHub pages and cloudflare pages, none of them works well for the TocSide feature. I don't know what happend, So anything wrong with my config file?

Here is my gh-page.yml file.
```yml
name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
