### ISSUE TITLE
automatically switch themes

### ISSUE THREAD

**Issue by Neon-44** [reorx/hugo-PaperModX#54]
on Firefox, it doesn't automatically switch themes but you have to reload the page.

would it be possible to automatically recognise when the user switches to dark mode and adjust the webpage?

**Comment by sukalaper** [comment]
> on Firefox, it doesn't automatically switch themes but you have to reload the page.
> 
> would it be possible to automatically recognise when the user switches to dark mode and adjust the webpage?

Hello, here I also use Firefox but it works to switch themes well. First, can I have a look at your ``config.yml``?

**Comment by Neon-44** [comment]
sure, here you go:
left out baseURL etc.
but i have declared further up:
```
baseURL: []
languageCode: []
title: []
theme: PaperModX
```
copy paste from config (deleted commented out parts for readability)
```
params:
 TocSide: right
 ShowToc: true
 ShowReadingTime: true
 DefaultTheme: auto

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

```
